frames:
  - rotateX: -30
    rotateY:
      min: -20
      max: 20
    translateZ: -1.0
    numFrames: 6

  - rotateX: -35
    rotateY:
      min: -20
      max: 20
    translateZ: -1.0
    numFrames: 6

  - rotateX: -45
    rotateY:
      min: -20
      max: 20
    translateZ: -1.0
    numFrames: 6

# - rotateX: -40
#   rotateY:
#     min: -30
#     max: 30
#   translateZ: -0.7
#   numFrames: 6

# - rotateX: -20
#   rotateY:
#     min: -30
#     max: 30
#   translateZ: -0.7
#   numFrames: 6


planning:
  maxDegreesPerSecond: 60

