detector_options:
    div_factor: 1.4               # Division factor used for graduated non-convexity
    use_absolute_scale: false               # Measure distance in absolute scale (1) or in scale relative to the diameter of the model (0)
    max_corr_dist: 0.01               # Maximum correspondence distance (also see comment of USE_ABSOLUTE_SCALE)
    iteration_number: 200               # Maximum number of iteration
    tuple_scale: 0.95               # Similarity measure used for tuples of feature points.
    tuple_max_cnt: 1000               # Maximum tuple numbers.
    interpoint_scale: 0.002               # guess of interpoint scale in the input cloud
    feature_radius_multiplier: 5                # width multiplier for feature extraction